package com.babyorm.db;

import com.babyorm.annotation.PK;
import com.babyorm.annotation.TableName;

@TableName("no_autogen")
public class EntityWithNonAutogenPK {
    @PK(autogenerated = false)
    private String pk;
    private String name;
}