package com.babyorm.db;

import com.babyorm.annotation.PK;
import com.babyorm.keyProvider.RandomUUIDStringKeyProvider;

public class Parent {
    @PK(autogenerated = false, keyProvider = RandomUUIDStringKeyProvider.class)
    private String pk;

    private String name;

    public String getPk() {
        return pk;
    }

    public void setPk(String pk) {
        this.pk = pk;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
