package com.babyorm.annotation;

import com.babyorm.ColumnValueProvider;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation to denote that the value for the column should be generated on save if the value is null.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface Generated {

    /**
     * Whether this value is generated in the database or if it's generated by this orm.
     *
     * If it is database generated, for instance a column created with the AUTO_INCREMENT option in mysql, we will
     * @return
     */
    boolean isDatabaseGenerated();

    /**
     * The canonical class name of a class that implements {@link com.babyorm.ColumnValueProvider}
     * @return The canonical class name of the {@link com.babyorm.ColumnValueProvider}
     */
    Class<? extends ColumnValueProvider> columnValueProvider() default ColumnValueProvider.class;
}
