package com.babyorm.annotation;

import com.babyorm.KeyProvider;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * This annotation identifies the primary key of the entity
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface PK {
    /**
     * Whether new primary keys are generated on insert or not.
     * If they are NOT, you must supply a {@link KeyProvider} to the repo to generate your own damn keys
     */
    boolean autogenerated() default true;
}