package com.babyorm.annotation;

import com.babyorm.ColumnValueProvider;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * This annotation identifies the primary key of the entity
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface PK {
    /**
     * Whether new primary keys are generated on insert or not.
     * If they are NOT, you must supply a {@link com.babyorm.ColumnValueProvider} to the repo to generate your own damn keys
     */
    boolean autogenerated() default true;

    /**
     * A key provider for this field, or a multi key provider for an entity with multiple keys
     */
    Class<? extends ColumnValueProvider> keyProvider() default ColumnValueProvider.class;
}